# CodeRabbit Configuration for Aleph-w
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: "en-US"

reviews:
  # Enable reviews on ALL branches, not just default
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  # Enable auto review
  auto_review:
    enabled: true
    drafts: false
    # Review PRs only to master, main, develop, and release branches
    base_branches:
      - "^master$"
      - "^main$"
      - "^develop$"
      - "^release/.*"

  pre_merge_checks:
    docstrings:
      mode: off
    custom_checks:
      - name: "Header Docstring Coverage"
        mode: warning
        instructions: |
          Compute documentation coverage only for library headers in this PR.

          Scope:
          - Include files matching: **/*.{h,H,hpp,hxx,hh}
          - Exclude paths: Tests/**, Examples/**, docs/**, .github/**, scripts/**, Testing/**, build*/**, cmake-build-*/**

          For in-scope changed declarations that should be documented (public classes/structs/functions/methods/templates), compute:
          coverage = documented / total * 100

          Pass condition:
          - coverage >= 80%
          - If no in-scope declarations changed, mark as passed.
  
  path_instructions:
    - path: "**/*"
      instructions: |
        General review guidelines:
        - Provide feedback in these sections: "Must fix", "Should fix", "Nice to have".
        - Prioritize: correctness (UB, data races, lifetime), security, regressions, then performance.
        - If the PR changes behavior, require tests or explain why they don't apply.
        - Avoid out-of-scope suggestions (massive refactors, global formatting) unless necessary.

    - path: "**/*.{h,H,hpp,hxx,hh}"
      instructions: |
        This is a C++ header file in the Aleph-w library.
        Review: algorithm correctness, memory leaks, exception safety,
        correct template usage, and adherence to project style
        (no 'using namespace std' in headers).

    - path: "**/*.{c,C,cc,cpp,cxx}"
      instructions: |
        C++ implementation file. Verify correctness and performance.

    - path: "Tests/**"
      instructions: |
        Test file with Google Test. Check edge case coverage,
        that tests are deterministic, and no memory leaks.

chat:
  auto_reply: true
