#!/bin/bash

ALEPHDIR=/home/alex/tmp/aleph-w

list=`ls *.[hcHC]`

rm -rf $ALEPHDIR
mkdir -p $ALEPHDIR
cp $list COPYRIGHT aleph-foot.html aleph-header.html grupos.doxy aleph.dox funcional.dox favicon.png logo.png capas.png $ALEPHDIR
cp -r doc $ALEPHDIR/

cd $ALEPHDIR
for f in $list
do
    name=`basename $f`
    echo $f
    mv $f $f.tmp
    cat COPYRIGHT $f.tmp > $f 
    rm $f.tmp
done

doxygen aleph.dox
mkdir -p doc/html/images
cp favicon.png logo.png capas.png doc/html/

