/** \fn traverse()

    \class DynList

    \brief Recorre condicionalmente el contenedor y ejecuta una operation
    mientras ésta retorne true.

    \param[in] operation operación a ejecutar sobre cada elemento. Si
      la operación retorna false, entonces se detiene el recorrido. De
      lo contrario, el recorrido continua sobre el siguiente elemento

      \return true si todos los elementos fueron recorridos; lo que
      imprica que la operación retorno true para todos los
      elementos. false de lo contrarion

    @ingroup Funcional
 */

/** \fn 

    \brief

    \param

    @ingroup Funcional
 */
