
/*
                          Aleph_w

  Data structures & Algorithms
  version 2.0.0b
  https://github.com/lrleon/Aleph-w

  This file is part of Aleph-w library

  Copyright (c) 2002-2026 Leandro Rabindranath Leon

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

/** @file huffman_tree.h
 *  @brief Serialized Huffman tree generated by Examples/write_huffman.C.
 *
 *  Output of `Huffman_Encoder_Engine::save_tree_in_array_of_chars()`
 *  (`tpl_binNodeUtils.H`) over the built-in Lorca poem. Not included by
 *  anything in the library; kept as a worked example of the array format
 *  `load_tree_from_array()` reads back.
 *
 *  @see tpl_binNodeUtils.H save_tree_in_array_of_chars() load_tree_from_array()
 */

# ifndef HUFFMAN_TREE_H
# define HUFFMAN_TREE_H

// 195 bits declaration
const unsigned char huffman_cdp [25] = {
  176, 193, 12, 219, 108, 134, 217, 204, 108, 198, 182, 217, 96, 216, 102,
  219, 48, 204, 198, 182, 217, 216, 48, 219, 6
};

// `huffman_cdp` is `const`, so it gets internal linkage by default in C++
// (one private copy per translation unit); `huffman_k` is an array of
// pointers to `const char`, not a `const` array, so without `inline` it
// gets external linkage and a "multiple definition" link error when this
// header is included from more than one translation unit.
//
// Two entries below are the two bytes of the poem's only accented letter
// ("Antoñito"), written as a hex escape rather than the raw byte: the
// generator (put_tree_keys_in_array() in tpl_binNodeUtils.H) treats a
// multi-byte UTF-8 character as two separate one-byte Huffman symbols, and
// a raw lone continuation/lead byte is not valid UTF-8 text on its own,
// which has already once caused it to be silently mangled into U+FFFD by
// some text-handling step. The hex escape produces the identical byte at
// compile time while keeping this file valid UTF-8 source text.
inline const char * huffman_k[] = {
"", "", "", "e", "a", "", "", "", "", "b", "", "j", "", "", "", "\xC3", "D", "Y", "", "H", "!", "", ".", "", "", "", "F", "", "?", ":", "", "T", "", "\xB1", "", "", "Z", "", "V", "", "", "U", "O", "M", "i", "", "n", "r", "", "", "", "", "t", "", "", "", "C", "z", "p", "", "g", "q", "o", " ", "", "", "", "u", "", "", "", "h", "", "E", "L", "", "", "f", "B", "A", "v", "", "c", "d", "", "", "l", "s", "", "", "", ",", "", "y", "G", "m", "\n", nullptr };

# endif // HUFFMAN_TREE_H
