#!/usr/bin/env ruby
# -*- coding: iso-8859-1 -*-

require 'fileutils'
version = File.new('version.txt').read

note = %Q<
/*
                          Aleph_w

  Data structures & Algorithms
  version #{version.chomp}
  https://github.com/lrleon/Aleph-w

  This file is part of Aleph-w library

  Copyright (c) 2002-2022 Leandro Rabindranath Leon

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program. If not, see <https://www.gnu.org/licenses/>.
*/
>

pat = /\/\* Aleph-w.*\*\//m

def process_file(file_name, pat, note)
  file = File.new(file_name).read
  file.gsub(pat, note)
end

def collect_files(paths)
  files = []
  paths.each do |path|
    if File.directory?(path)
      Dir.glob("#{path}/*.{h,H,c,C,cc}").each { |f| files << f }
    elsif File.file?(path)
      files << path
    end
  end
  files
end

if ARGV.empty?
  files = collect_files(['Tests', 'Examples'])
  files.each do |file_name|
    puts "Processing: #{file_name}"
    result = process_file(file_name, pat, note)
    File.write("#{file_name}.tmp", result)
    FileUtils.mv("#{file_name}.tmp", file_name)
  end
elsif ARGV.length == 1 && !ARGV[0].include?('/')
  file_name = ARGV[0]
  puts process_file(file_name, pat, note)
else
  files = collect_files(ARGV)
  files.each do |file_name|
    puts "Processing: #{file_name}"
    result = process_file(file_name, pat, note)
    File.write("#{file_name}.tmp", result)
    FileUtils.mv("#{file_name}.tmp", file_name)
  end
end
