
/*
                          Aleph_w

  Data structures & Algorithms
  version 2.0.0b
  https://github.com/lrleon/Aleph-w

  This file is part of Aleph-w library

  Copyright (c) 2002-2026 Leandro Rabindranath Leon

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/


/**
 * @file special_ctors_test.cc
 * @brief Tests for the constructors generated by the Special_Ctors macro.
 *
 * The iterator-pair constructor used to accept any type, so an integer pair
 * such as `X<int>(3, 7)` selected it and failed inside the macro on `*it`.
 * These tests check that integer pairs never select it, that a count/value
 * constructor wins over it, and that real ranges are still accepted.
 */
#include <gtest/gtest.h>

#include <cstddef>
#include <iterator>
#include <type_traits>
#include <vector>

#include <ahDry.H>
#include <htlist.H>
#include <polygon.H>
#include <tpl_array.H>
#include <tpl_arrayHeap.H>
#include <tpl_arrayQueue.H>
#include <tpl_arrayStack.H>
#include <tpl_dynArray.H>
#include <tpl_dynArrayHeap.H>
#include <tpl_dynBinHeap.H>
#include <tpl_dynDlist.H>
#include <tpl_dynListQueue.H>
#include <tpl_dynListStack.H>
#include <tpl_dynSetHash.H>
#include <tpl_dynSetTree.H>
#include <tpl_dynSkipList.H>
#include <tpl_hash.H>
#include <tpl_interval_tree.H>
#include <tpl_odhash.H>
#include <tpl_olhash.H>

using namespace Aleph;

namespace
{
  /// Minimal container with a count/value constructor and Special_Ctors.
  template <typename T>
  class Count_Value_Probe
  {
    Array<T> items;

  public:
    Count_Value_Probe() = default;

    Count_Value_Probe(const size_t n, const T & value) : items(n, value) {}

    T & append(const T & item) { return items.append(item); }

    template <class Operation>
    void for_each(Operation op) const { items.for_each(op); }

    [[nodiscard]] const Array<T> & get_items() const noexcept { return items; }

    Special_Ctors(Count_Value_Probe, T);
  };

  /// Forward iterator with only `*`, `++` and `!=`, and no iterator_traits.
  class Bare_Iterator
  {
    const int * pos;

  public:
    explicit Bare_Iterator(const int * p) noexcept : pos(p) {}

    const int & operator * () const noexcept { return *pos; }

    Bare_Iterator & operator ++ () noexcept
    {
      ++pos;
      return *this;
    }

    bool operator != (const Bare_Iterator & other) const noexcept
    {
      return pos != other.pos;
    }
  };

  static_assert(not std::input_iterator<Bare_Iterator>,
                "the probe must be weaker than std::input_iterator");

  /// True if `C` can be built from a pair of `I` values or lvalues.
  template <class C, typename I = int>
  constexpr bool accepts_integer_pair =
    std::is_constructible_v<C, I, I> or std::is_constructible_v<C, I &, I &>;
} // namespace

TEST(SpecialCtors, IntegerPairsNeverSelectTheIteratorConstructor)
{
  // No other constructor takes two integers, so the pair is rejected with a
  // "no matching constructor" error instead of failing inside the macro.
  static_assert(not accepts_integer_pair<ArrayQueue<int>>);
  static_assert(not accepts_integer_pair<FixedQueue<int>>);
  static_assert(not accepts_integer_pair<ArrayStack<int>>);
  static_assert(not accepts_integer_pair<FixedStack<int>>);
  static_assert(not accepts_integer_pair<ArrayHeap<int>>);
  static_assert(not accepts_integer_pair<DynDlist<int>>);
  // DynList inherits the constructors of SpecialCtors (ah-dry.H), whose
  // iterator constructor had no constraint: DynList<int>(3, 7) chose it.
  static_assert(not accepts_integer_pair<DynList<int>>);
  static_assert(not accepts_integer_pair<DynListQueue<int>>);
  static_assert(not accepts_integer_pair<DynListStack<int>>);
  static_assert(not accepts_integer_pair<DynSetTree<int>>);
  static_assert(not accepts_integer_pair<DynSetHash<int>>);
  static_assert(not accepts_integer_pair<HashSet<int>>);
  static_assert(not accepts_integer_pair<ODhashTable<int>>);
  static_assert(not accepts_integer_pair<OLhashTable<int>>);
  static_assert(not accepts_integer_pair<DynIntervalTree<int>>);
  static_assert(not accepts_integer_pair<Polygon>);

  static_assert(not accepts_integer_pair<ArrayQueue<size_t>, size_t>);
  static_assert(not accepts_integer_pair<DynDlist<size_t>, size_t>);
  static_assert(not accepts_integer_pair<DynList<size_t>, size_t>);
  static_assert(not accepts_integer_pair<DynSetTree<size_t>, size_t>);
  static_assert(not accepts_integer_pair<OLhashTable<size_t>, size_t>);

  // DynArray has a count/value constructor: the pair reaches it and builds
  // n copies of the value, as std::vector does.
  static_assert(accepts_integer_pair<DynArray<int>>);
  static_assert(accepts_integer_pair<DynArray<size_t>, size_t>);
  const DynArray<int> repeated(3, 7);
  ASSERT_EQ(repeated.size(), 3u);
  EXPECT_EQ(repeated.access(0), 7);
  EXPECT_EQ(repeated.access(2), 7);

  // DynSkipList has a (seed, probability) constructor: the pair selects it,
  // not a range of items, and 7 is not a probability in (0, 1).
  EXPECT_THROW(DynSkipList<int>(3, 7), std::domain_error);
  DynSkipList<int> skip(3, 0.25);
  EXPECT_TRUE(skip.is_empty());

  // The heaps keep their variadic item constructor, which binds lvalues only:
  // two int variables are two items, while two literals are rejected.
  static_assert(not std::is_constructible_v<DynBinHeap<int>, int, int>);
  static_assert(not std::is_constructible_v<DynArrayHeap<int>, int, int>);
  int a = 3, b = 7;
  DynBinHeap<int> bin_heap(a, b);
  DynArrayHeap<int> array_heap(a, b);
  EXPECT_EQ(bin_heap.size(), 2u);
  EXPECT_EQ(array_heap.size(), 2u);
}

TEST(SpecialCtors, CountValueConstructorWinsOverTheIteratorTemplate)
{
  const Count_Value_Probe<int> literals(3, 7);
  EXPECT_EQ(literals.get_items(), (Array<int>{7, 7, 7}));

  int n = 2, value = 9;
  const Count_Value_Probe<int> lvalues(n, value);
  EXPECT_EQ(lvalues.get_items(), (Array<int>{9, 9}));

  const size_t m = 2, v = 5;
  const Count_Value_Probe<size_t> same_type(m, v);
  EXPECT_EQ(same_type.get_items(), (Array<size_t>{5, 5}));
}

TEST(SpecialCtors, AcceptsIteratorsWithoutIteratorTraits)
{
  const int raw[] = {4, 5, 6};

  const Count_Value_Probe<int> probe(Bare_Iterator(raw), Bare_Iterator(raw + 3));
  EXPECT_EQ(probe.get_items(), (Array<int>{4, 5, 6}));

  DynDlist<int> list(Bare_Iterator(raw), Bare_Iterator(raw + 3));
  ASSERT_EQ(list.size(), 3u);
  EXPECT_EQ(list.get_first(), 4);
  EXPECT_EQ(list.get_last(), 6);
}

TEST(SpecialCtors, BuildsFromVectorPointerAndAlephRanges)
{
  const std::vector<int> vec = {3, 1, 2};
  const int raw[] = {3, 1, 2};
  const DynList<int> aleph = {3, 1, 2};

  const DynDlist<int> from_vector(vec.begin(), vec.end());
  const DynDlist<int> from_pointers(raw, raw + 3);
  const DynDlist<int> from_aleph(aleph.begin(), aleph.end());
  for (const DynDlist<int> * list : {&from_vector, &from_pointers, &from_aleph})
    {
      ASSERT_EQ(list->size(), 3u);
      EXPECT_EQ(list->get_first(), 3);
      EXPECT_EQ(list->get_last(), 2);
    }

  const DynArray<int> array(raw, raw + 3);
  ASSERT_EQ(array.size(), 3u);
  EXPECT_EQ(array(0), 3);
  EXPECT_EQ(array(2), 2);

  ArrayQueue<int> queue(aleph.begin(), aleph.end());
  ASSERT_EQ(queue.size(), 3u);
  EXPECT_EQ(queue.front(), 3);
  EXPECT_EQ(queue.rear(), 2);

  const DynSetTree<int> set(vec.begin(), vec.end());
  ASSERT_EQ(set.size(), 3u);
  EXPECT_EQ(set.min(), 1);
  EXPECT_EQ(set.max(), 3);
}
