/*
                          Aleph_w

  Data structures & Algorithms
  https://github.com/lrleon/Aleph-w

  This file is part of Aleph-w library

  Copyright (c) 2002-2026 Leandro Rabindranath Leon

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

/**
 * @file fuzz_csv_utility.cc
 * @brief Fuzz the general CSV reader and writer in parse-csv.H.
 */

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <sstream>
#include <string>

#include <parse-csv.H>

/**
 * @brief Parse arbitrary CSV and round-trip generated fields through the writer.
 * @param data Fuzzer-generated bytes.
 * @param size Number of available bytes.
 * @return Zero when parsing completes and generated fields round-trip.
 * @note Processes at most 512 input bytes and eight generated fields.
 */
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
  size = std::min(size, size_t{512});
  const char delimiters[] = {',', ';', '\t'};
  const char delimiter = delimiters[size == 0 ? 0 : data[0] % 3];
  const char *bytes = size == 0 ? "" : reinterpret_cast<const char *>(data);
  const std::string input(bytes, size);

  std::istringstream arbitrary(input);
  (void) Aleph::csv_read_row(arbitrary, delimiter);

  Aleph::Array<std::string> fields;
  size_t cursor = size == 0 ? 0 : 1;
  const size_t field_count = size < 2 ? 1 : 1 + data[1] % 8;
  if (size >= 2)
    cursor = 2;

  for (size_t i = 0; i < field_count; ++i)
    {
      const size_t length = cursor < size ? data[cursor++] % 33 : 0;
      const size_t available = std::min(length, size - cursor);
      fields.append(std::string(bytes + cursor, available));
      cursor += available;
    }

  std::ostringstream output;
  Aleph::csv_write_row(output, fields, delimiter);
  std::istringstream written(output.str());
  const auto parsed = Aleph::csv_read_row(written, delimiter);
  if (parsed.size() != fields.size())
    std::abort();
  for (size_t i = 0; i < fields.size(); ++i)
    if (parsed(i) != fields(i))
      std::abort();

  return 0;
}
