/*
                          Aleph_w

  Data structures & Algorithms
  version 2.0.0b
  https://github.com/lrleon/Aleph-w

  This file is part of Aleph-w library

  Copyright (c) 2002-2026 Leandro Rabindranath Leon

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

/**
 * @file ca_export_example.cc
 * @brief Practical Phase-11 export pipeline for Conway's Game of Life.
 *
 * Usage:
 *
 *   ca_export_example [steps] [output-dir] [pattern]
 *
 * Patterns: glider (default), blinker, r-pentomino, gosper.
 *
 * The example writes:
 *
 *   - `frames/frame_XXXX.ppm`: one binary PPM frame per step.
 *   - `final.rle`: compact Conway RLE of the final frame.
 *   - `final.csv`: numeric matrix snapshot.
 *   - `final.json`: JSON matrix snapshot.
 *   - `final.tex`: TikZ picture of the final frame.
 *   - `frames/manifest.csv`: frame sequence manifest.
 */

#include <cerrno>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <string>
#include <utility>
#include <vector>

#include <ca-engine-utils.H>
#include <ca-frame-stream.H>
#include <ca-io.H>
#include <ca-tikz.H>
#include <ca-traits.H>
#include <tpl_ca_lattice.H>
#include <tpl_ca_storage.H>

using namespace Aleph::CA;

namespace
{
  using Grid = Lattice<Dense_Cell_Storage<int, 2>, ToroidalBoundary>;

  bool parse_steps(const char *text, std::size_t &out)
  {
    if (text == nullptr or text[0] == '-')
      return false;
    errno = 0;
    char *end = nullptr;
    const unsigned long long value = std::strtoull(text, &end, 10);
    if (errno == ERANGE or end == text or *end != '\0'
        or value > std::numeric_limits<std::size_t>::max())
      return false;
    out = static_cast<std::size_t>(value);
    return true;
  }

  std::vector<std::pair<int, int>> pattern_for(const std::string &name)
  {
    if (name == "blinker")
      return {{0, -1}, {0, 0}, {0, 1}};
    if (name == "r-pentomino")
      return {{0, 1}, {0, 2}, {1, 0}, {1, 1}, {2, 1}};
    if (name == "gosper")
      return {
        {4,0}, {4,1}, {5,0}, {5,1},
        {2,12}, {2,13}, {3,11}, {3,15}, {4,10}, {4,16},
        {5,10}, {5,14}, {5,16}, {5,17}, {6,10}, {6,16},
        {7,11}, {7,15}, {8,12}, {8,13},
        {0,24}, {1,22}, {1,24}, {2,20}, {2,21}, {3,20},
        {3,21}, {4,20}, {4,21}, {5,22}, {5,24}, {6,24},
        {2,34}, {2,35}, {3,34}, {3,35}
      };
    return {{0, 1}, {1, 2}, {2, 0}, {2, 1}, {2, 2}};
  }

  void stamp(Grid &grid,
             ca_index_t row,
             ca_index_t col,
             const std::vector<std::pair<int, int>> &cells)
  {
    const auto rows = static_cast<ca_index_t>(grid.size(0));
    const auto cols = static_cast<ca_index_t>(grid.size(1));
    for (const auto &[dr, dc] : cells)
      {
        const ca_index_t r = ((row + dr) % rows + rows) % rows;
        const ca_index_t c = ((col + dc) % cols + cols) % cols;
        grid.set({r, c}, 1);
      }
  }

  void write_final_exports(const std::filesystem::path &dir,
                           const Grid &frame,
                           const std::string &pattern,
                           std::size_t steps)
  {
    {
      std::ofstream out(dir / "final.rle");
      RLE_Write_Options opts;
      opts.name = pattern + " after " + std::to_string(steps) + " steps";
      opts.comment = "Generated by Aleph::CA ca_export_example";
      opts.trim_dead_border = true;
      write_rle(out, frame, opts);
    }
    {
      std::ofstream out(dir / "final.csv");
      write_csv(out, frame);
    }
    {
      std::ofstream out(dir / "final.json");
      JSON_Write_Options opts;
      opts.pretty = true;
      opts.rule = "B3/S23";
      write_json(out, frame, opts);
    }
    {
      std::ofstream out(dir / "final.tex");
      Rect_Tikz_Options opts;
      opts.cell_size = 0.18;
      opts.grid_colour = "black!25";
      render_lattice_tikz(out,
                          frame,
                          Binary_Tikz_Palette<int>{0, "white", "black"},
                          opts);
    }
  }
}

int main(int argc, char **argv)
{
  std::size_t steps = 32;
  if (argc >= 2 and not parse_steps(argv[1], steps))
    {
      std::cerr << "Invalid steps argument\n";
      return 1;
    }

  const std::filesystem::path out_dir = argc >= 3 ? argv[2] : "ca_export_output";
  const std::string pattern = argc >= 4 ? argv[3] : "glider";

  ca_size_t rows = 32;
  ca_size_t cols = pattern == "gosper" ? 80 : 48;
  if (pattern == "gosper")
    rows = 40;

  Grid grid({rows, cols}, 0);
  stamp(grid,
        static_cast<ca_index_t>(rows / 3),
        static_cast<ca_index_t>(cols / 4),
        pattern_for(pattern));

  auto engine = make_gol_engine(std::move(grid));

  const auto frames_dir = out_dir / "frames";
  Frame_Stream_Options stream_opts;
  stream_opts.directory = frames_dir;
  stream_opts.prefix = "frame";
  stream_opts.format = Frame_Output_Format::PPM;
  stream_opts.zero_pad = 4;

  Directory_Frame_Sink frames(stream_opts);
  for (std::size_t t = 0; t <= steps; ++t)
    {
      frames.accept(engine.steps_run(), engine.frame());
      if (t != steps)
        engine.step();
    }
  frames.flush();

  std::filesystem::create_directories(out_dir);
  write_final_exports(out_dir, engine.frame(), pattern, steps);

  std::cout << "Exported " << frames.written_frames().size()
            << " frames to " << frames_dir << '\n';
  std::cout << "Final snapshots: " << (out_dir / "final.rle") << ", "
            << (out_dir / "final.csv") << ", "
            << (out_dir / "final.json") << ", "
            << (out_dir / "final.tex") << '\n';
  std::cout << "Video hint: " << frames.montage_command_hint("life.mp4", 24)
            << '\n';

  return 0;
}
